apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      labels:
        app: my_app
    spec:
      containers:
      - name: my_app
        image: jfmarquez23/python_devops:latest
        ports:
        - containerPort: 80