---
apiVersion: v1
kind: Deployment
metadata:
  name: microservicio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: jfmarquez23/python_devops:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "clave secreta"
        - name: DEBUG
          value: "False"
