apiVersion: v1
kind: Service
metadata:
  name: microservicio
  metadata:
  name: demo-devops-python
spec:
  selector:
    app: django
  ports:
   - port: 8000
     targetPort: 80
  type: LoadBalancer