apiVersion: v1
kind: Service
metadata:
  name: microservicio
  metadata:
  name: demo-devops-python
spec:
  selector:
    app: django
  ports:
   - port: 80
     targetPort: 8000
  type: LoadBalancer