apiVersion: v1
kind: Service
metadata:
  name: my_app_service
  metadata:
  name: my_app
spec:
  selector:
    app: my_app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 8001
  type: LoadBalancer