name: CI/CD Pipeline

on:
  push:
    branches:
      - main  #Nombre de la rama
  pull_request:
    branches:
      - master

jobs:
  build-test-analysis-docker-kubernetes:
    runs-on: ubuntu-latest

    #CodeCheck
    steps:
    - name: Chequear codigo
      uses: actions/checkout@v2
 
    #CodeBuild
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #Migracion BDD
    - name: Migracion BDD
      run: python manage.py migrate

    #Test
    - name: Ejecutar Test
      run: |
        python manage.py test

    # Code Coverage
    - name: Cobertura de codigo
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report  
  
    #Construir Imagen y Subirla en DockerHub
    - name: Login Docker_Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD  }}

    - name: Construir imagen y subirla
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/python_devops:latest  # Nombre de la imagen

    # Escaneo Vulnerabilidades imagen
    - name: Scanear la imagen
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'jfmarquez23/python_devops:latest'
        format: 'table'
        
    # Despliegue en Minicube kubernetes  
    # Instalar Minikube
    - name: Instalar Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    # Instalar kubectl
    - name: Instalar kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    # Iniciar Minikube
    - name: Iniciar Minikube
      run: |
        minikube start
          
    #Desplegar en Minikube
    - name: Deploy to Minikube
      run: |
        kubectl apply -f K8S/deployment.yml
        kubectl apply -f K8S/service.yml
        
    # Validar estado 
    - name: Comprobar estado del cluster
      run: |
        minikube status
        
    # información de los servicios desplegados en el clúster 
    - name: Informacion Cluster
      run: |
        kubectl get services

    # URL Load Balancer 
    - name: Info Load Balancer
      run: |
        minikube service my-app --url